### ISSUE TITLE
Issuer url not changing 

### ISSUE THREAD

**Issue by Jaymn** [omarhoblos/swiss-on-fhir#276]
**Describe the bug**
`authWellKnownEndPoints` gets shared with other issuers after changing issuer in `env.js`. Occurs if the client id stays the same. Ex, if `localhost:9300` and `localhost:9400` uses swiss as the Client ID.

**To Reproduce**
1. Set env.js variables to first auth endpoint with an initial client id 
2. go through authentication process, and go back to home screen
3. log out of session
4. change env.js issuer variable to second auth endpoint while keeping the same client id 
5. start authentication process, will go to initial auth endpoint instead of new auth endpoint

**Expected behavior**
When changing env.js, it should go to the new issuer endpoint even if the client id stays the same.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 103.0.5060.114

**Comment by omarhoblos** [comment]
The issue does not affect Docker deployments as they do not have an easy of altering their issuer URL in the same way as running Swiss from source (using node). The issue is caused by the way the OIDC client remove session variables, where there is a chance that it stores old session details and overwrites new values with old ones cached. Simply running a `sessionStorage.clear()` resolves the issue. 

[PR](https://github.com/omarhoblos/swiss-on-fhir/pull/294)
